name: TwRestart
version: 1.1
main: ru.twrestart.TwRestart
api-version: 1.16
authors:
  - Tex.Admin servera TownCraft
commands:
  resser:
    description: Перезагрузка сервера с таймером
    usage: /resser [секунды]
    permission: twrestart.restart
  twrestart:
    description: Основная команда плагина TwRestart
    usage: /twrestart reload
    permission: twrestart.admin
    aliases: [twr]