name: TwRestart
version: 1.1
main: ru.twrestart.TwRestart
api-version: 1.16
authors:
  - Tex.Admin servera TownCraft
commands:
  resser:
    description: Перезагрузка сервера с таймером
    usage: /resser [секунды/cancel]
    permission: twrestart.restart
  twrestart:
    description: Основная команда плагина TwRestart
    usage: /twrestart reload
    permission: twrestart.admin
    aliases: [twr]

permissions:
  twrestart.restart:
    description: Позволяет запускать /resser [время].
    default: op
  twrestart.admin:
    description: Позволяет использовать /twrestart reload и /resser cancel.
    default: op